alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias cd..="cd .."
alias dotnet="dotnet.exe"
alias g="git"
alias gti="git"
alias qbprod="ssh -t -i qbdev ubuntu@tools.querobolsa.space 'docker exec -it querobolsa_prod_idle bundle exec rails c'"
alias dev="cd ~/devenv/"
alias forest="solano"
alias ybm="yarn && bundle && rails {db,seed}:migrate && RAILS_ENV=test rails {db,seed}:migrate"
alias rng="ranger"
