#!/bin/bash

########################
## VH Make and Change ##
##     directory      ##
########################

vSHORTHELP="usage: vhmc <directory name>"
vLOGHELP="usage: vhmc <directory name>"

if [[ $# -eq 0 ]]; then
	echo -e $vSHORTHELP
	return 1
fi

## this file is basecally this:
# mkcd () {
#   mkdir "$1"
#   cd "$1"
# }
##
# but if some gory modifications:
# https://unix.stackexchange.com/a/9124
##

while [ $# -gt 0 ]
do
	case "$1" in
		-h)
			echo -e $vLOGHELP
			;;
		*/..|*/../)
			cd -- "$1"
			;; # that doesn't make any sense unless the directory already exists
		/*/../*)
			(cd "${1%/../*}/.." && mkdir -p "./${1##*/../}") && cd -- "$1"
			;;
		/*)
			mkdir -p "$1" && cd "$1"
			;;
		*/../*)
			(cd "./${1%/../*}/.." && mkdir -p "./${1##*/../}") && cd "./$1"
			;;
		../*)
			(cd .. && mkdir -p "${1#.}") && cd "$1"
			;;
		*)
			mkdir -p "./$1" && cd "./$1"
			;;
	esac

	# shift for next dir
	shift
done
