#!/bin/bash
tTITLE="Time's up!"
tMSG="The time has ended."
tURGENCY="normal"
tSHORTHELP="usage: vhtimer <TIME> [TITLE [MESSAGE]]\n
for more information run 'vhtimer'"
tLONGHELP="usage: vhtimer <TIME> [TITLE [MESSAGE]]\n
\n
\t	TIME\t\tin \`sleep\` format, e.g.:\n
\t	\t	\t	\t	5s - for 5 seconds\n
\t	\t	\t	\t	5m - for 5 minutes\n
\t	\t	\t	\t	5h - for 5 hours\n
\t	\t	\t	\t	5d - for 5 days\n
\t	TITLE\t\tis optional, default is \'$tTITLE\'\n
\t	MESSAGE\tis optional, default is \'$tMSG\'\n"

if [[ $# -eq 0 ]]; then
    echo -e $tLONGHELP
elif [[ $# -gt 0 ]]; then
	if [[ $1 =~ [1-9][0-9]*[smhd] ]]; then
		tTIME=$1
	else
		echo -e $tSHORTHELP
		exit 0
	fi
	if [[ $# -gt 1 ]]; then
		tTITLE=$2

		if [[ $# -gt 2 ]]; then
			tMSG=$3
		fi
	fi
	eval sleep $tTIME && notify-send --urgency="$tURGENCY" "$tTITLE" "$tMSG"
fi
# vim: ts=8 sw=8 sts=8
